package com.love.lxinxin.greendao.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.love.lxinxin.greendao.data.bean.User;
import com.love.lxinxin.greendao.data.bean.Event;

import com.love.lxinxin.greendao.data.dao.UserDao;
import com.love.lxinxin.greendao.data.dao.EventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig eventDaoConfig;

    private final UserDao userDao;
    private final EventDao eventDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Event.class, eventDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        eventDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

}
