package com.love.lxinxin.greendao.data.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.love.lxinxin.greendao.data.bean.Event;
import com.love.lxinxin.greendao.data.bean.User;

import com.love.lxinxin.greendao.data.dao.EventDao;
import com.love.lxinxin.greendao.data.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig userDaoConfig;

    private final EventDao eventDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        eventDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
